### PR TITLE
Updated SolrClient::query() return type to SolrQueryResponse

### PR DESCRIPTION
**Pull request by jsmith07**

### CODE REVIEW

**Comment by pjmazenot** [comment]
Oh I see, the title of your PR is right but you edited the wrong function (request instead of query)!

Please send an updated PR.

**Comment by jsmith07** [comment]
sorry, somehow I got off a method when changing it on a few of the driver versions. Got them fixed now.

**Comment by pjmazenot** [comment]
Thanks @jsmith07! The 2.2.1 and 2.4.0 are not updated with your initial fix so if you want to send a last commit for that I'll be able to close the PR faster.

**Comment by jsmith07** [comment]
For me the PR shows that all 5 have the change.

**Comment by pjmazenot** [comment]
Ok I'm closing it then. Thanks!

**Pull request merged**
